env:
  global:
    - secure: zhnL40+Knr3hIMNnpfNO+Y9jbxwVcjuRRVkZ79+Lz1hT2rpnFJAZHXVXZ6KQJnxKnGJGDSoC7JnsvIe1yL0cKfVhid8FGo4EZfA4ceb6KtdLn8apnSvjX1F8sI/bBu2PM79BIxNNkQZWlk6J9xFICFaUSJO5SbxQ3175aGy8H0hpDsmbEMn4GL7R+TD50r/EqeFVtqEWjxijX0I4PmAIZTux1uHjx/uMyo0iXRzZDtaMIaQvhnQfdiOuBN1fyF/q/GYDxQDmbO9Zjv0cJ/kzND5N2uUQQp3VTUE/V/xWHtwirsmuhPDuiFdyfBpx9mY86UhhFmCGobntytqFU7EkzZHLS8IAPHH9q7Ly9/XogwKEKkVn43VOJ1yAGPdSDd/Q7et+vDGKDJ2U7+9jOOTGOIFqlcVkzfrD8QxfI/kz7kauXU9IGbEtv1+BL+ZhTQfl4gVKAAsAPhZ2POmN1oD3K0NfplaIF3pQiPa+/2FzptUzVBrXX7MmwPsqRQA8Sgikbsa7Z5aLM24Zklv3Vubgo0v3KSAacX0TlEn/UDJCZIFONaoKa6PrC3AkQLHj7zYu9w9Lkea/q6fXxx3/0oYUmUQB4hbtS1JMO5kCJaalSJPpfZSlrEQZovw3PyQo83POwlNE2fX8qnC6vnRMKux2O07z//qhxjuLVQisqVW1il4=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/yoyo.org_ips
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
