env:
  global:
    - secure: BjCOmGBVrdS+PkPYXzmySpfZXGaGOyvBmnjY5OpysZ2WR+kuIkfekRilf91rTulgBg0ty29f9PPPcfM4tt/NVVSVi+FfbRejca2evk3Sw0REKc8GCCudvUmrbsBVurWKarweXvOmy3mm1MsuBi1+o5i1tiE8I50084HlWCvWz81M0oE680VTzJTkMuoyhq1STkhBgJVEmoUZgdrhSajpkEoFINxQ8Kut3KIvHKF9vUfppawcA2wqP85JqRlVx8J89lX82VYRNyyVvjotGX6Er0SwlyvhYAW+ni+awViLB3wypI4nXgg1RrQT5KYzFg9JeBLnSKQW9h3JlfCDoeRjD84WX6az9XG6WaWbl/zkOsWU8DOyXtbI21JctD/PbXSwMUaWXbrEMg3pyqbzuVAh/k6qW0IM2QVQLQCBODbVlK4nftcLouF0GkGtycezjo8XzmcNA06zO1S1Hn40L2NMIR7V2YdIfHLfqbjifrHnSTdx5sGZPk0SYZxaPhX+W+oj5XJbvViM7sT19KHkxXDDI64S4trLvNuwRqeivapX6LT6OLCcLD/TrTvlMljpalc2ZHRUrKEd4VTDWVTGzr3phne/LBwTVAVRd6pLkdg5dr6nOExVNe9cj5RAQAhAz9E1QKlLl0I9dM264PvScAzSoYAwkGrgNiH7KN4eQDIfXBc=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/yoyo.org_ips
    - GIT_BRANCH: master
    - WHITELISTING_LOCATION: https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/dev-center/whitelisting/whitelisting.py
    - UPDATE_LOCATION: https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/repository-structure/master/update.py
    - ADMINISTATION_LOCATION: https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/repository-structure/master/administration.py

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests
  - wget "${WHITELISTING_LOCATION}" -o /dev/null -O whitelisting.py && chmod +x whitelisting.py
  - if [[ ! -f .admin ]]; then wget "${UPDATE_LOCATION}" -o /dev/null -O update.py && chmod +x update.py; else echo "No need to download/update update.py."; fi
  - if [[ ! -f .admin ]]; then wget "${ADMINISTATION_LOCATION}" -o /dev/null -O administration.py && chmod +x administration.py; else echo "No need to download/update administration.py."; fi

script:
  - python3 ./update.py

notifications:
  on_success: change
  on_failure: always
