env:
  global:
    - secure: XrqTejjjpuGB/ky2QYDRMuT2jyxQb32S4Fwyq6XTbNeogWOrCgbghYU+FfO+ClIWFl4mkpPBPquURr3WW6esFseap76OxLij1QYS4SrywtOU22s/TVAGDFwBgIKvjeQjgSsWZMZyjlvZjZqe1QW6ior1XEku9/6LQoa4GMO/4TyCoAtf8/Vi1G5hA8gCTDWToWYUIlJeO9RazY27v89S4hhbjFx6RcZRcxp5KuseQzBAfjkv/W6lSo+veD97LRtiFCt+dlCEr2KGC/YmLlebQ/wY5HjhheyBIzyy5wYoK/Ua5wSE3WLL/abnj0U14kDcvpJYieqDTfLmH9u5ZVry8tCq+NS7eL0+9KCU8v2ofTSD3fAYRofccHi6y3bnam5l2cN8Zvwh1qTK9XA7kXnOUaZCfHVZaRvTMWs+iafVzFU8ZqM/aHbBG3rfiX+sIrJjJ6i91kuDz+sxV1bl4DUGPrePuVJi0XHjsKovzW2l99Ro9wZCE9x9T4Pkbvl+bihYDCjrH1L4lyfsyaX3vhitDCn17gl6r/lLZGvSTnrk/K1IzDbLDnOjUJy6+UvjTYzJ2zklX5cB2TNh8c+d/szxi+kWgh0q1OpJOeJXJNH0bj+C0QdaqCBXwpW9E4cp45BR3VqV7lZN2QOWFG2nD8CK1g7tzj7kmBN2n1Z4POPPL9M=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/yoyo.org_ips
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
