env:
  global:
    - secure: Td58WcvnyggB2ElUI1LVT4nXevPgN0IoNeOMnokXB0KDCfQT2DHAjOCJjMbZitpkU7PYv0nD5D59e+s6Cj0hNji4mCPFI4y4AuTdxzeYru3i+1f3HlEHYjsR33TGbB8opgJkMf8nbsTmRkaE4qlYhH134DziiJyLJmx4QiU5O1/zIMJ62FIx1TRDmWQyqCflybE7McyaGjJdTK/sDyJs9qhSXzNcbztxQ0e3lYLZ9PQUy0NqsAL65/XMcyixtBHbzc+C8OWVEGXrXtdKKK92S+FDZcnJ6sQkoYQ33DwykoBo6ydjmpv7dI8+LuktkraWnJsdwfORkFENOdR8N+3D5R7jRCrQ39xzT1HX+aRrdOEvI9wgJEUVX33sluOfmua321IRquhZOSVv/Gt8mfdL3LMv+41PkIOKZpnAgyGYNngoAyza50KOmTA0uVmZNPMKq5vb5SprjEVg7YveYZcxF717fvgiD8RAP9Sp/ugEq3AtlddCnL3zqKpiAyTVX0Z4CXV7L9xhvH+jqwKhqXK8/vbNG+jd3roI2W4GBIbJGeNReTGymw+bo5IfJtcxrh3WU22rp9zs7QQxOdgp7mW/04Jx3zcz12urpTkk1fTb9mCXsTDw2aKANdRSuiymaM3Jdrr9WzQ6iFy7fAsevnlgq00/IchP5mgh8AF1E8QIubk=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/yoyo.org_ips
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
