env:
  global:
    - secure: mYTqaL0tzdctZ287s9OW4FM3VIcW7Ze4mycOH2f6emxYcMBVJHFdXAJ0WxCLuilr/oCesTwL0QWA80m5uq1IdRQdrGHQ/C2+Afvle0uKMDbkIo9kQmZwI/r7fwmodf0GugI90nuxJoXdljO1dN1CbEewoPwaB75F6X99+yl+Q77hcbkBFUcX+WW5OdWqITD4Hpxaa7Ou5VH/gI9CsrEF61Qfuw6nZvGXfnlx993RjzuId1E+lcW/wuRpLAhKP3Vse0gKw38hncilAp7rvGYM1UrH2B6VJp/ry9Zn5q1G9RiXAORN8cL3tWTJjqTJLTP3KxP3DAb3BjuJDz7CG7ehghtmnLwfrlGF09vRfovs9MPYKax79pl+YNERbKT1IGJ2gwdm5w+wBgBEH9YNnKOmNsMvJQtd7t1k/rzccca14LmRe2VpYAN1SizSfnziJfNXfe/1dcVyCw20dgmVo86mVDFnrIJ4pHVr7RgAirppKPrl1Z+Es+Ls7J9Fb6uuHIwcJsuxxrYogGVYLSsq+ot4j3mzH1n9WnS1PvOmAI1yqPsNEn0sRql3G3ZCq6/dYlkOs787OPN6W2kegngvlabgeXmfWPL/vCVvHys6Lg48K4r/SND5TgEs2nVTm4+AipytSWhc7NMfzbxeV88gVZTf1b529xYFTw982gNGTJkz4Ck=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: mitchellkrog@gmail.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/yoyo.org_ips
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
