env:
  global:
    - secure: KqHgJoD0s57ffn/d05jiLarwBvf76oyRXnBjzyyBnkLQrKu3k9VluCyM4fmj1BTl4vGRnjGdxGLzgXknxcMavODS8IJEFaZTMqazfQCe4ZBqfo8H7eDblg2/fEM+hj0m+gelUl2j2UI6fbVdcwZa4cipmga10eRJpF17Cabu18mgYYbYwC3p2q65MgY3FaV78xicoVeie60AYSFBZ/cseZUxN4OkAZEvqrNHmY1QmrVnMW7LO9F4WqlGOgG5SVklC+3nzQd80sCj0Tw8jbud/M5Pr0nL5bYMidjnHClV0iwEWyCTswBhEZgg8OWElmkVY85fRHXz4tXIQDT5bKXiveE+veZxzdQ5dfQUdL20dG5jMF5hnzeFrb8WkdHQhjupRhc67sTaBHuhLqMJTnQAHELq5msm2GFgqchNm8q1bBJcG/gaXjnsCle3DjB9rkaL3Lp3Jyd6LmuS59y0PqioWXnxLO5BfjQLiOvkmv8U7lnC4Z1x9W77DG6kV+U4mWM+hZWWtWV5AEd4GSeFDSlhlWr3+Jm9nz22ZFqNMT/uhD3vgkgYKAcj/s424IFv2KCCJLlJjmCkXOLg0CFqn4gkeIgxPhFRzUp+6i/IBtEBLo9gXsvufV+zHlxYUOkQtq72k5XXzdZq5XhXj/R8HQCjqELuMjgt+UB88DxhSYvjwik=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/yoyo.org_ips
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
