env:
  global:
    - secure: cmXy9CT3y90ib/LgNfSxm76B2BniyZe+xXmcAyB5A5DVF5hLhtzyFdQx9DuiLrPKHP9BN93ak0akZsPFNJpxfQwGAHy8dYAZoaf7GVSSMMbUIAIVO4nTkZfbeJTz2zjhuVdijAB1uzmsdgNpVsCQsdmXbroojO4PIKxVIsE0MB2yXHfmQiRjas53hxnD/YhmJVagj0rs6vAzYalYLyp7rnMJMZ1RJgZ+/5fkoi3WjkFeyRppvf1ZyG2lgxUkptus8aDYT3STB/gH/vS4a0akspyE/a/d2fzAxFl2pna+UyK+7+AicoOQWi891Ijvw4u3H15jaLXT+JcZkY75IzIMp2KHzYBFfrHRRroSRHBMieItIKVGIljpC50KMKzZWvDGQxzTIw8OoGdxn0kTqo+Annlv3USiv2Nko4A0igoWGnSlS5BIf0MKvSz7GFqLNB1QR8EPxOPq6fospjyOhJ3d0QwJ50OInN77Ykdp5LXoH39OQdjwl+Hemuhxjq5g5LetCEFnp5Tm+1lNlJYdV2WpNAKua3IziJAoOHJJeI7bi+VFqwf4K4i9giP1PKZCNtDc4WIVE/LjXq5VdfldjVGGuqdrH86JyruQGEEu485Hpn5Dmjr1J2ORGgVaxtHLXW+8bPWgyJ1SrgupkUSAlULvkX6ojgau+n2KnWjIJ68rgUw=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/yoyo.org_ips
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
