env:
  global:
    - secure: yb4xgT+zixt4Z7X0s3CFWq2V18ZjJEWu9c5BQBxuNbbNCNlq3GNOpQMkZW4FbCViNbaxmLBKc/DdSMrzM/HhOR2gr/NoAKE3+VNiVFAZDLYjwlX7F8ZF+dfOc80B8QomUnAEkNfpEeTC5K1v0PkSitvnOpl8N7jONQZLqszG/Ti9/2L3+xk7AFGaqkBtiHCqlzK0pW4HYz1U35iecZCM3rhJbaB6s/FkV8M7qIP2EE+/NriXMMwizpRHg+MLgEy+bmwFUFzl7AiaB9L/Qb4pJEA2BEd6kqAkQebYQflb/MpMyGDVwa+YC2vwdrdxjyrKdtybAvZ+r7zfyZKtJl/EVSgN8HrOx9lEpO/z06AV+BnylxRxCluQxFwwV97YJwvhPos3dI6Dj0anqlRQjRgowura2Wm0ubQlfaO9ux1UXi87Knamaahtg6narDY8qNFW6qjCvA7qK1a36H6qRhNjVEgsM19mpzvZ5pPDgYawCviT7pM8+6/lFk9wcmfNluVKmhNBviDgBrYQCxBQaqJGGqn1eG9QeuTayzQZj40A3ENFf5WmPGgp3AbSKwM1u6KMSIcCJbeLL//duW20rA/h4OkuAUIYMdvvsV8QI4zuS8ntZ/SOoYIC4H5aWTi3UIgXkpxHBftFXAzVg4oYoTbPcTptjfoFiSU/zill3xw2HOg=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/yoyo.org_ips
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
